version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=room_booking_system
      - SECRET_KEY=your_secret_key
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: room_booking_system
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
